name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
  
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  flutter_svg: ^2.0.10+1
  firebase_storage: ^11.7.7
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  image_picker: ^0.8.4+3
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo_t_3.png
  - assets/images/blue.png
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/background_1_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/images/logo_t_3.png
  - assets/images/white.png
  - assets/vectors/single_011_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/rectangle_11_x2.svg
  - assets/vectors/left_arrow_7_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/left_arrow_1_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/left_arrow_x2.svg
  - assets/vectors/ellipse_6_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/rectangle_111_x2.svg
  - assets/vectors/logout_x2.svg
  - assets/vectors/left_arrow_3_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/ellipse_91_x2.svg
  - assets/vectors/bell_531_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/left_arrow_2_x2.svg
  - assets/images/logo_t_3.png
  - assets/images/blue.png
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/path_6_x2.svg
  - assets/vectors/path_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/path_9_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/path_4_x2.svg
  - assets/vectors/path_1_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/path_10_x2.svg
  - assets/images/rectangle_18.png
  - assets/images/ellipse_12.png
  - assets/images/rectangle_181.png
  - assets/images/logo_t_3.png
  - assets/images/rectangle_182.png
  - assets/vectors/container_4_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/images/logo_t_3.png
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/bg_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/bg_1_x2.svg
  - assets/images/logo_t_3.png
  - assets/vectors/primary_1_x2.svg
  - assets/vectors/shape_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/primary_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/xmlid_28_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/images/plat.png
  - assets/images/logo_t_3.png
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/details_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/polygon_1_stroke_x2.svg
  - assets/vectors/background_x2.svg
  - assets/vectors/plat_1_x2.svg
  - assets/images/logo_t_3.png
  - assets/images/zu_idlsz_3_xlg.jpeg
  - assets/images/plkg_cs_boiw_4.jpeg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/polygon_1_stroke_1_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/images/logo_t_3.png
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/images/logo_t_3.png
  - assets/images/commande.jpeg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/add_1_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/location_1_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/container_11_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/container_8_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/polygon_1_stroke_3_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/container_13_x2.svg
  - assets/images/logo_t_3.png
  - assets/vectors/polygon_1_stroke_2_x2.svg
  - assets/vectors/container_7_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/container_5_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/container_9_x2.svg
  - assets/vectors/eye_slash_1_x2.svg
  - assets/images/tabbakhi_12.png
  - assets/vectors/icon_x2.svg
  - assets/vectors/shape_1_x2.svg
  - assets/vectors/super_g_x2.svg
  - assets/vectors/facebook_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/rectangle_3_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/images/ellipse_27.png
  - assets/images/logo_t_3.png
  - assets/images/image_1.png
  - assets/vectors/mask_group_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/ellipse_28_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/ellipse_24_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/ellipse_26_x2.svg
  - assets/vectors/ellipse_25_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/location_1_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/search_1_x2.svg
  - assets/vectors/ellipse_29_x2.svg
  - assets/vectors/ellipse_271_x2.svg
  - assets/images/logo_t_3.png
  - assets/images/ellipse_7.png
  - assets/images/ellipse_12.png
  - assets/images/ellipse_8.png
  - assets/images/ellipse_20.png
  - assets/images/ellipse_16.png
  - assets/images/ellipse_17.png
  - assets/vectors/container_3_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/container_6_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/heart_4_x2.svg
  - assets/vectors/heart_3_x2.svg
  - assets/vectors/ellipse_61_x2.svg
  - assets/vectors/ellipse_81_x2.svg
  - assets/vectors/ellipse_71_x2.svg
  - assets/vectors/heart_2_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/container_12_x2.svg
  - assets/vectors/heart_x2.svg
  - assets/vectors/container_10_x2.svg
  - assets/vectors/ellipse_201_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/heart_1_x2.svg
  - assets/vectors/ellipse_171_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/images/rectangle_5.jpeg
  - assets/images/logo_t_3.png
  - assets/images/rectangle_52.jpeg
  - assets/images/rectangle_53.jpeg
  - assets/images/rectangle_51.jpeg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/search_2_x2.svg
  - assets/vectors/location_11_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/images/white.png
  - assets/images/logo_t_3.png
  - assets/vectors/path_2_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/path_5_x2.svg
  - assets/vectors/path_7_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/path_3_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/path_8_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/images/logo_t_3.png
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/shopping_icon_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/rectangle_54_x2.svg
  - assets/vectors/rectangle_4_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/left_arrow_5_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/polygon_1_stroke_4_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/left_arrow_6_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/left_arrow_4_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/images/image_6.png
  - assets/images/tabbakhi_12.png

